-- Enable Clerk under Supabase Auth > Third-party Auth Providers.
-- Configure a Clerk JWT template named "supabase" with audience "authenticated".
create table if not exists public.dsa_progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  problem_number integer not null,
  status text not null default 'Todo' check (status in ('Todo', 'In progress', 'Solved')),
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, problem_number)
);

alter table public.dsa_progress
  drop constraint if exists dsa_progress_user_id_fkey;

alter table public.dsa_progress
  alter column user_id type text using user_id::text;

alter table public.dsa_progress enable row level security;

drop policy if exists "Users manage their own DSA progress" on public.dsa_progress;
create policy "Users manage their own DSA progress"
  on public.dsa_progress for all
  using ((auth.jwt() ->> 'sub') = user_id)
  with check ((auth.jwt() ->> 'sub') = user_id);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
add column if not exists email text;

alter table public.profiles
add column if not exists display_name text;

alter table public.profiles
add column if not exists created_at timestamptz not null default now();

alter table public.profiles
add column if not exists updated_at timestamptz not null default now();

alter table public.profiles enable row level security;

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'display_name', ''))
  on conflict (id) do update
  set email = excluded.email,
      display_name = excluded.display_name,
      updated_at = now();
  return new;
end;
$$;

insert into public.profiles (id, email, display_name)
select id, email, coalesce(raw_user_meta_data ->> 'display_name', '')
from auth.users
on conflict (id) do update
set email = excluded.email,
    display_name = excluded.display_name,
    updated_at = now();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
