-- Activate Clerk's native Supabase integration and add its Clerk domain under
-- Supabase Auth > Third-party Auth Providers before using authenticated queries.
create table if not exists public.dsa_progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  problem_number integer not null,
  status text not null default 'Todo' check (status in ('Todo', 'In progress', 'Solved')),
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, problem_number)
);

alter table public.dsa_progress
  drop constraint if exists dsa_progress_user_id_fkey;

drop policy if exists "Users manage their own DSA progress" on public.dsa_progress;

alter table public.dsa_progress
  alter column user_id type text using user_id::text;

alter table public.dsa_progress enable row level security;

create policy "Users manage their own DSA progress"
  on public.dsa_progress for all
  using ((auth.jwt() ->> 'sub') = user_id)
  with check ((auth.jwt() ->> 'sub') = user_id);

grant select, insert, update, delete on public.dsa_progress to authenticated;
grant usage, select on sequence public.dsa_progress_id_seq to authenticated;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
add column if not exists email text;

alter table public.profiles
add column if not exists display_name text;

alter table public.profiles
add column if not exists created_at timestamptz not null default now();

alter table public.profiles
add column if not exists updated_at timestamptz not null default now();

alter table public.profiles enable row level security;

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'display_name', ''))
  on conflict (id) do update
  set email = excluded.email,
      display_name = excluded.display_name,
      updated_at = now();
  return new;
end;
$$;

insert into public.profiles (id, email, display_name)
select id, email, coalesce(raw_user_meta_data ->> 'display_name', '')
from auth.users
on conflict (id) do update
set email = excluded.email,
    display_name = excluded.display_name,
    updated_at = now();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create table if not exists public.personal_notes (
  user_id text primary key,
  content text not null default '' check (char_length(content) <= 100000),
  updated_at timestamptz not null default now()
);

alter table public.personal_notes enable row level security;

drop policy if exists "Users manage their own personal notes" on public.personal_notes;
create policy "Users manage their own personal notes"
  on public.personal_notes for all
  using ((auth.jwt() ->> 'sub') = user_id)
  with check ((auth.jwt() ->> 'sub') = user_id);

grant select, insert, update on public.personal_notes to authenticated;

create table if not exists public.group_chat_messages (
  id bigint generated by default as identity primary key,
  user_id text not null,
  content text not null check (char_length(content) between 1 and 4000),
  created_at timestamptz not null default now()
);

drop index if exists public.group_chat_messages_created_idx;

alter table public.group_chat_messages enable row level security;

drop policy if exists "Signed-in users can read group chat" on public.group_chat_messages;
create policy "Signed-in users can read group chat"
  on public.group_chat_messages for select
  to authenticated
  using (true);

drop policy if exists "Signed-in users can send as themselves" on public.group_chat_messages;
create policy "Signed-in users can send as themselves"
  on public.group_chat_messages for insert
  to authenticated
  with check ((auth.jwt() ->> 'sub') = user_id);

grant select, insert on public.group_chat_messages to authenticated;
grant usage, select on sequence public.group_chat_messages_id_seq to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'group_chat_messages'
  ) then
    alter publication supabase_realtime add table public.group_chat_messages;
  end if;
end;
$$;

notify pgrst, 'reload schema';
