-- Configure Clerk's third-party auth integration in Supabase before using authenticated queries.
create table if not exists public.dsa_progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  problem_number integer not null,
  status text not null default 'Todo' check (status in ('Todo', 'In progress', 'Solved')),
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, problem_number)
);

alter table public.dsa_progress
  drop constraint if exists dsa_progress_user_id_fkey;

drop policy if exists "Users manage their own DSA progress" on public.dsa_progress;

alter table public.dsa_progress
  alter column user_id type text using user_id::text;

alter table public.dsa_progress enable row level security;

create policy "Users manage their own DSA progress"
  on public.dsa_progress for all
  using ((auth.jwt() ->> 'sub') = user_id)
  with check ((auth.jwt() ->> 'sub') = user_id);

grant select, insert, update, delete on public.dsa_progress to authenticated;
grant usage, select on sequence public.dsa_progress_id_seq to authenticated;

create table if not exists public.dsa_problem_content (
  problem_number integer primary key check (problem_number between 1 and 250),
  description text not null check (char_length(description) between 1 and 10000),
  constraints text[] not null default '{}',
  examples jsonb not null default '[]'::jsonb
    check (jsonb_typeof(examples) = 'array'),
  updated_at timestamptz not null default now()
);

alter table public.dsa_problem_content enable row level security;
drop policy if exists "Anyone can read DSA problem content" on public.dsa_problem_content;
create policy "Anyone can read DSA problem content"
  on public.dsa_problem_content for select
  to anon, authenticated
  using (true);

grant select on public.dsa_problem_content to anon, authenticated;
grant select, insert, update, delete on public.dsa_problem_content to service_role;

create table if not exists public.dsa_problem_test_cases (
  id bigint generated by default as identity primary key,
  problem_number integer not null
    references public.dsa_problem_content(problem_number) on delete cascade,
  case_number smallint not null check (case_number between 1 and 10),
  stdin text not null check (char_length(stdin) <= 10000),
  expected_output text not null check (char_length(expected_output) <= 10000),
  unique (problem_number, case_number)
);

alter table public.dsa_problem_test_cases enable row level security;
revoke all on public.dsa_problem_test_cases from anon, authenticated;
grant select, insert, update, delete on public.dsa_problem_test_cases to service_role;
grant usage, select on sequence public.dsa_problem_test_cases_id_seq to service_role;

insert into public.dsa_problem_content
  (problem_number, description, constraints, examples)
values
  (
    1,
    'Given an integer array and a target value, find the indices of two distinct elements whose values add up to the target. Print the two indices in ascending order. Each input has exactly one answer.',
    array['2 <= n <= 100000', 'Each array value and the target fit in a signed 32-bit integer'],
    jsonb_build_array(jsonb_build_object(
      'input', E'4 9\n2 7 11 15',
      'output', '0 1'
    ))
  ),
  (
    2,
    'Read two lowercase strings and print true if the second string is a rearrangement of the first; otherwise print false.',
    array['1 <= string length <= 50000', 'Strings contain lowercase English letters'],
    jsonb_build_array(jsonb_build_object(
      'input', E'anagram\nnagaram',
      'output', 'true'
    ))
  ),
  (
    3,
    'Group the given words so that each group contains words made from the same letters. Sort the words in each group, then sort the groups by their first word. Print one group per line.',
    array['1 <= number of words <= 10000', 'Words contain lowercase English letters'],
    jsonb_build_array(jsonb_build_object(
      'input', E'6\neat tea tan ate nat bat',
      'output', E'ant nat tan\nate eat tea\nbat'
    ))
  ),
  (
    4,
    'Given a list of integers and an integer k, print the k values that occur most often. If frequencies tie, print the smaller value first.',
    array['1 <= n <= 100000', '1 <= k <= number of distinct values'],
    jsonb_build_array(jsonb_build_object(
      'input', E'6 2\n1 1 1 2 2 3',
      'output', '1 2'
    ))
  ),
  (
    5,
    'Given an integer array, print a new array where each position contains the product of every input value except the value at that position. Do not use division.',
    array['2 <= n <= 100000', 'The product of values fits in a signed 64-bit integer'],
    jsonb_build_array(jsonb_build_object(
      'input', E'4\n1 2 3 4',
      'output', '24 12 8 6'
    ))
  )
on conflict (problem_number) do nothing;

insert into public.dsa_problem_test_cases
  (problem_number, case_number, stdin, expected_output)
values
  (1, 1, E'4 9\n2 7 11 15', '0 1'),
  (2, 1, E'anagram\nnagaram', 'true'),
  (3, 1, E'6\neat tea tan ate nat bat', E'ant nat tan\nate eat tea\nbat'),
  (4, 1, E'6 2\n1 1 1 2 2 3', '1 2'),
  (5, 1, E'4\n1 2 3 4', '24 12 8 6')
on conflict (problem_number, case_number) do nothing;

insert into public.dsa_problem_content
  (problem_number, description, constraints, examples)
values
  (6, 'Read a line and determine whether it is a palindrome after ignoring non-alphanumeric characters and letter case. Print true or false.', array[]::text[], jsonb_build_array(jsonb_build_object('input', 'A man, a plan, a canal: Panama', 'output', 'true'))),
  (7, 'Read n and an integer array. Print every unique triple whose values sum to zero, one triple per line, with values ascending and triples lexicographically ordered.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'6\n-1 0 1 2 -1 -4', 'output', E'-1 -1 2\n-1 0 1'))),
  (8, 'Read n and non-negative heights. Print the maximum water area that can be contained between two bars.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'9\n1 8 6 2 5 4 8 3 7', 'output', '49'))),
  (9, 'Read n and non-negative bar heights. Print the total amount of rain water trapped between the bars.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'12\n0 1 0 2 1 0 1 3 2 1 2 1', 'output', '6'))),
  (10, 'Read n and daily stock prices. Print the maximum profit from one buy followed by one sell; print zero if no profit is possible.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'6\n7 1 5 3 6 4', 'output', '5'))),
  (11, 'Read a string and print the length of its longest substring containing no repeated characters.', array[]::text[], jsonb_build_array(jsonb_build_object('input', 'abcabcbb', 'output', '3'))),
  (12, 'Read a string of uppercase letters and integer k. Print the longest substring length achievable by changing at most k characters to the same letter.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'ABAB 2', 'output', '4'))),
  (13, 'Read source and target strings on separate lines. Print the shortest substring of the source containing every target character with its multiplicity, or an empty line if none exists.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'ADOBECODEBANC\nABC', 'output', 'BANC'))),
  (14, 'Read a string of brackets and print true if every opening bracket is closed in the correct order; otherwise print false.', array[]::text[], jsonb_build_array(jsonb_build_object('input', '()[]{}', 'output', 'true'))),
  (15, 'Process push x, pop, top, and getMin commands for a stack. Print a result only for top and getMin commands. The input begins with the command count.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'7\npush -2\npush 0\npush -3\ngetMin\npop\ntop\ngetMin', 'output', E'-3\n0\n-2'))),
  (16, 'Read space-separated integer tokens in reverse Polish notation and print the evaluated result. Division truncates toward zero.', array[]::text[], jsonb_build_array(jsonb_build_object('input', '2 1 + 3 *', 'output', '9'))),
  (17, 'Read n daily temperatures. For each day print how many days must pass until a warmer temperature, or zero if none follows.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'8\n73 74 75 71 69 72 76 73', 'output', '1 1 4 2 1 1 0 0'))),
  (18, 'Read n, a sorted integer array, and a target. Print the target index if present, otherwise print -1.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'6 9\n-1 0 3 5 9 12', 'output', '4'))),
  (19, 'Read row count, column count, target, then a row-major sorted matrix. Print true if the target is present, otherwise false.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'3 4 3\n1 3 5 7\n10 11 16 20\n23 30 34 60', 'output', 'true'))),
  (20, 'Read n, the number of hours h, and n banana-pile sizes. Print the minimum integer eating speed that finishes all piles within h hours.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'4 8\n3 6 7 11', 'output', '4'))),
  (21, 'Read n and n linked-list values. Print the values in reverse order on one line.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'5\n1 2 3 4 5', 'output', '5 4 3 2 1'))),
  (22, 'Read lengths n and m followed by two sorted lists. Print their merged sorted values on one line.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'3 3\n1 2 4\n1 3 4', 'output', '1 1 2 3 4 4'))),
  (23, 'Read n and list values. Reorder the list as first, last, second, second-last, and so on, then print the values.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'5\n1 2 3 4 5', 'output', '1 5 2 4 3'))),
  (24, 'Read n, k, and a list. Remove the kth node from the end (k is one-based) and print the remaining values.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'5 2\n1 2 3 4 5', 'output', '1 2 3 5'))),
  (25, 'Simulate an LRU cache. Input starts with capacity and command count, followed by put key value or get key commands. Print each get result, or -1 for a missing key.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'2 5\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2', 'output', E'1\n-1'))),
  (26, 'Read a binary tree in level order using null for missing nodes. Invert the tree and print its level-order values, omitting trailing nulls.', array[]::text[], jsonb_build_array(jsonb_build_object('input', '4 2 7 1 3 6 9', 'output', '4 7 2 9 6 3 1'))),
  (27, 'Read a binary tree in level order using null for missing nodes. Print its maximum depth.', array[]::text[], jsonb_build_array(jsonb_build_object('input', '3 9 20 null null 15 7', 'output', '3'))),
  (28, 'Read a binary tree in level order using null for missing nodes. Print each level on its own line, with values separated by spaces.', array[]::text[], jsonb_build_array(jsonb_build_object('input', '3 9 20 null null 15 7', 'output', E'3\n9 20\n15 7'))),
  (29, 'Read a binary tree in level order using null for missing nodes. Print true if it is a valid binary search tree, otherwise false.', array[]::text[], jsonb_build_array(jsonb_build_object('input', '2 1 3', 'output', 'true'))),
  (30, 'Read k followed by a binary search tree in level order using null for missing nodes. Print the kth smallest value, where k is one-based.', array[]::text[], jsonb_build_array(jsonb_build_object('input', '3 5 3 6 2 4 null null 1', 'output', '3'))),
  (31, 'Read n and distinct integers. Print all subsets, one per line, with values ascending; order subsets by size and then lexicographically. Print {} for the empty subset.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'2\n1 2', 'output', E'{}\n1\n2\n1 2'))),
  (32, 'Read candidate count and target, then positive candidate values. Print unique combinations summing to the target, one per line, with values ascending and lines lexicographically ordered.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'4 7\n2 3 6 7', 'output', E'2 2 3\n7'))),
  (33, 'Read n distinct integers. Print every permutation on its own line, with permutations in lexicographic order.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'3\n1 2 3', 'output', E'1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1'))),
  (34, 'Read grid dimensions, one uppercase-letter row per line, and a word. Print true if the word can be formed from adjacent horizontal or vertical cells without reusing a cell.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'3 4\nABCE\nSFCS\nADEE\nABCCED', 'output', 'true'))),
  (35, 'Read n and print the number of distinct ways to place n queens on an n by n board so no two queens attack each other.', array[]::text[], jsonb_build_array(jsonb_build_object('input', '4', 'output', '2'))),
  (36, 'Read grid dimensions and rows of 0 and 1 characters. Print the number of four-directionally connected islands of 1s.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'4 5\n11000\n11000\n00100\n00011', 'output', '3'))),
  (37, 'Read an undirected graph as vertex count, edge count, and one-based edge pairs. Clone the graph and print its adjacency list in vertex order with each neighbor list sorted.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'4 3\n1 2\n2 3\n3 4', 'output', E'1: 2\n2: 1 3\n3: 2 4\n4: 3'))),
  (38, 'Read a grid of 0 (empty), 1 (fresh), and 2 (rotten) oranges. Each minute, rotten oranges infect adjacent fresh oranges. Print the minutes until all can rot, or -1.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'3 3\n2 1 1\n1 1 0\n0 1 1', 'output', '4'))),
  (39, 'Read course count n and prerequisite count m, followed by pairs course prerequisite. Print true if all courses can be completed, otherwise false.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'2 1\n1 0', 'output', 'true'))),
  (40, 'Read vertex count n and edge count m, followed by undirected edge pairs using zero-based vertices. Print true if the graph is connected and has no cycle, otherwise false.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'5 4\n0 1\n0 2\n0 3\n1 4', 'output', 'true'))),
  (41, 'Read n and print the number of distinct ways to climb n stairs when each move is one or two stairs.', array[]::text[], jsonb_build_array(jsonb_build_object('input', '5', 'output', '8'))),
  (42, 'Read n and non-negative house values. Print the maximum amount that can be robbed without robbing adjacent houses.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'4\n2 7 9 3', 'output', '11'))),
  (43, 'Read coin count and amount, followed by positive coin denominations. Print the fewest coins needed to make the amount, or -1 if impossible.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'3 11\n1 2 5', 'output', '3'))),
  (44, 'Read n and an integer sequence. Print the length of its longest strictly increasing subsequence.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'8\n10 9 2 5 3 7 101 18', 'output', '4'))),
  (45, 'Read a string, dictionary size, and dictionary words. Print true if the string can be segmented into dictionary words, otherwise false.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'leetcode\n2\nleet code', 'output', 'true'))),
  (46, 'Read grid row count m and column count n. Print the number of paths from top-left to bottom-right when each move is right or down.', array[]::text[], jsonb_build_array(jsonb_build_object('input', '3 7', 'output', '28'))),
  (47, 'Read two strings on separate lines. Print the length of their longest common subsequence.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'abcde\nace', 'output', '3'))),
  (48, 'Read n daily stock prices. Print the maximum profit when any number of transactions are allowed but selling must be followed by a one-day cooldown.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'5\n1 2 3 0 2', 'output', '3'))),
  (49, 'Read n balloon values. Print the maximum coins obtainable by bursting all balloons; bursting i earns left * value[i] * right, with outside values treated as 1.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'4\n3 1 5 8', 'output', '167'))),
  (50, 'Read a string and a pattern on separate lines. The pattern supports . for any one character and * for zero or more of the preceding character. Print true if it matches the entire string.', array[]::text[], jsonb_build_array(jsonb_build_object('input', E'aab\nc*a*b', 'output', 'true')))
on conflict (problem_number) do nothing;

insert into public.dsa_problem_test_cases
  (problem_number, case_number, stdin, expected_output)
values
  (6, 1, 'A man, a plan, a canal: Panama', 'true'),
  (7, 1, E'6\n-1 0 1 2 -1 -4', E'-1 -1 2\n-1 0 1'),
  (8, 1, E'9\n1 8 6 2 5 4 8 3 7', '49'),
  (9, 1, E'12\n0 1 0 2 1 0 1 3 2 1 2 1', '6'),
  (10, 1, E'6\n7 1 5 3 6 4', '5'),
  (11, 1, 'abcabcbb', '3'),
  (12, 1, 'ABAB 2', '4'),
  (13, 1, E'ADOBECODEBANC\nABC', 'BANC'),
  (14, 1, '()[]{}', 'true'),
  (15, 1, E'7\npush -2\npush 0\npush -3\ngetMin\npop\ntop\ngetMin', E'-3\n0\n-2'),
  (16, 1, '2 1 + 3 *', '9'),
  (17, 1, E'8\n73 74 75 71 69 72 76 73', '1 1 4 2 1 1 0 0'),
  (18, 1, E'6 9\n-1 0 3 5 9 12', '4'),
  (19, 1, E'3 4 3\n1 3 5 7\n10 11 16 20\n23 30 34 60', 'true'),
  (20, 1, E'4 8\n3 6 7 11', '4'),
  (21, 1, E'5\n1 2 3 4 5', '5 4 3 2 1'),
  (22, 1, E'3 3\n1 2 4\n1 3 4', '1 1 2 3 4 4'),
  (23, 1, E'5\n1 2 3 4 5', '1 5 2 4 3'),
  (24, 1, E'5 2\n1 2 3 4 5', '1 2 3 5'),
  (25, 1, E'2 5\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2', E'1\n-1'),
  (26, 1, '4 2 7 1 3 6 9', '4 7 2 9 6 3 1'),
  (27, 1, '3 9 20 null null 15 7', '3'),
  (28, 1, '3 9 20 null null 15 7', E'3\n9 20\n15 7'),
  (29, 1, '2 1 3', 'true'),
  (30, 1, '3 5 3 6 2 4 null null 1', '3'),
  (31, 1, E'2\n1 2', E'{}\n1\n2\n1 2'),
  (32, 1, E'4 7\n2 3 6 7', E'2 2 3\n7'),
  (33, 1, E'3\n1 2 3', E'1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1'),
  (34, 1, E'3 4\nABCE\nSFCS\nADEE\nABCCED', 'true'),
  (35, 1, '4', '2'),
  (36, 1, E'4 5\n11000\n11000\n00100\n00011', '3'),
  (37, 1, E'4 3\n1 2\n2 3\n3 4', E'1: 2\n2: 1 3\n3: 2 4\n4: 3'),
  (38, 1, E'3 3\n2 1 1\n1 1 0\n0 1 1', '4'),
  (39, 1, E'2 1\n1 0', 'true'),
  (40, 1, E'5 4\n0 1\n0 2\n0 3\n1 4', 'true'),
  (41, 1, '5', '8'),
  (42, 1, E'4\n2 7 9 3', '11'),
  (43, 1, E'3 11\n1 2 5', '3'),
  (44, 1, E'8\n10 9 2 5 3 7 101 18', '4'),
  (45, 1, E'leetcode\n2\nleet code', 'true'),
  (46, 1, '3 7', '28'),
  (47, 1, E'abcde\nace', '3'),
  (48, 1, E'5\n1 2 3 0 2', '3'),
  (49, 1, E'4\n3 1 5 8', '167'),
  (50, 1, E'aab\nc*a*b', 'true')
on conflict (problem_number, case_number) do nothing;

insert into public.dsa_problem_content
  (problem_number, description, constraints, examples)
select expanded.problem_number, base.description, base.constraints, base.examples
from generate_series(51, 250) as expanded(problem_number)
join public.dsa_problem_content as base
  on base.problem_number = ((expanded.problem_number - 1) % 50) + 1
on conflict (problem_number) do nothing;

insert into public.dsa_problem_test_cases
  (problem_number, case_number, stdin, expected_output)
select expanded.problem_number, base.case_number, base.stdin, base.expected_output
from generate_series(51, 250) as expanded(problem_number)
join public.dsa_problem_test_cases as base
  on base.problem_number = ((expanded.problem_number - 1) % 50) + 1
on conflict (problem_number, case_number) do nothing;

do $$
declare
  missing_problems integer;
begin
  select count(*)
  into missing_problems
  from generate_series(1, 250) as expected(problem_number)
  where not exists (
    select 1 from public.dsa_problem_content content
    where content.problem_number = expected.problem_number
  ) or not exists (
    select 1 from public.dsa_problem_test_cases test_case
    where test_case.problem_number = expected.problem_number
  );

  if missing_problems > 0 then
    raise exception 'Problem data setup is incomplete: % problem(s) are missing descriptions or test cases.', missing_problems;
  end if;
end;
$$;

create table if not exists public.profiles (
  user_id text primary key,
  email text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
add column if not exists user_id text;

alter table public.profiles
add column if not exists email text;

alter table public.profiles
add column if not exists display_name text;

alter table public.profiles
add column if not exists created_at timestamptz not null default now();

alter table public.profiles
add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if exists (
    select 1
    from pg_attribute
    where attrelid = 'public.profiles'::regclass
      and attname = 'id'
      and not attisdropped
  ) then
    alter table public.profiles drop constraint if exists profiles_pkey;
    alter table public.profiles drop constraint if exists profiles_id_fkey;
    alter table public.profiles alter column id drop not null;
    execute 'update public.profiles set user_id = id::text where user_id is null';
  end if;
end;
$$;

create unique index if not exists profiles_user_id_uidx
  on public.profiles (user_id);

alter table public.profiles
  alter column user_id set not null;

alter table public.profiles enable row level security;

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
  on public.profiles for select
  using ((auth.jwt() ->> 'sub') = user_id);

drop policy if exists "Signed-in users can read public profile metadata" on public.profiles;
create policy "Signed-in users can read public profile metadata"
  on public.profiles for select
  to authenticated
  using (true);

drop policy if exists "Users can create their own profile" on public.profiles;
create policy "Users can create their own profile"
  on public.profiles for insert
  with check ((auth.jwt() ->> 'sub') = user_id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using ((auth.jwt() ->> 'sub') = user_id)
  with check ((auth.jwt() ->> 'sub') = user_id);

revoke all on public.profiles from authenticated;
grant select (user_id, display_name) on public.profiles to authenticated;
grant insert on public.profiles to authenticated;
grant update (user_id, display_name) on public.profiles to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (user_id, email, display_name)
  values (new.id::text, new.email, coalesce(new.raw_user_meta_data ->> 'display_name', ''))
  on conflict (user_id) do update
  set email = excluded.email,
      display_name = excluded.display_name,
      updated_at = now();
  return new;
end;
$$;

insert into public.profiles (user_id, email, display_name)
select id::text, email, coalesce(raw_user_meta_data ->> 'display_name', '')
from auth.users
on conflict (user_id) do update
set email = excluded.email,
    display_name = excluded.display_name,
    updated_at = now();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create table if not exists public.personal_notes (
  id bigint generated by default as identity primary key,
  user_id text not null,
  title text not null default 'Untitled note',
  content text not null default '' check (char_length(content) <= 100000),
  updated_at timestamptz not null default now()
);

alter table public.personal_notes
  add column if not exists id bigint generated by default as identity;

alter table public.personal_notes
  add column if not exists title text not null default 'Untitled note';

do $$
declare
  primary_key_name text;
begin
  select conname into primary_key_name
  from pg_constraint
  where conrelid = 'public.personal_notes'::regclass
    and contype = 'p';

  if primary_key_name is not null and primary_key_name <> 'personal_notes_pkey' then
    execute format('alter table public.personal_notes drop constraint %I', primary_key_name);
  end if;
end;
$$;

alter table public.personal_notes
  drop constraint if exists personal_notes_pkey;

alter table public.personal_notes
  add constraint personal_notes_pkey primary key (id);

alter table public.personal_notes enable row level security;

drop policy if exists "Users manage their own personal notes" on public.personal_notes;
create policy "Users manage their own personal notes"
  on public.personal_notes for all
  using ((auth.jwt() ->> 'sub') = user_id)
  with check ((auth.jwt() ->> 'sub') = user_id);

grant select, insert, update on public.personal_notes to authenticated;
grant usage, select on sequence public.personal_notes_id_seq to authenticated;

create or replace function public.create_personal_notes_for_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.personal_notes (user_id)
  select new.user_id
  where not exists (
    select 1 from public.personal_notes where user_id = new.user_id
  );
  return new;
end;
$$;

drop trigger if exists create_personal_notes_for_profile on public.profiles;
create trigger create_personal_notes_for_profile
  after insert on public.profiles
  for each row execute procedure public.create_personal_notes_for_profile();

insert into public.personal_notes (user_id)
select user_id
from public.profiles
where not exists (
  select 1
  from public.personal_notes existing_note
  where existing_note.user_id = profiles.user_id
);

create table if not exists public.group_chat_messages (
  id bigint generated by default as identity primary key,
  user_id text not null,
  content text not null check (char_length(content) between 1 and 4000),
  created_at timestamptz not null default now()
);

drop index if exists public.group_chat_messages_created_idx;

alter table public.group_chat_messages enable row level security;

drop policy if exists "Signed-in users can read group chat" on public.group_chat_messages;
create policy "Signed-in users can read group chat"
  on public.group_chat_messages for select
  to authenticated
  using (true);

drop policy if exists "Signed-in users can send as themselves" on public.group_chat_messages;
create policy "Signed-in users can send as themselves"
  on public.group_chat_messages for insert
  to authenticated
  with check ((auth.jwt() ->> 'sub') = user_id);

grant select, insert on public.group_chat_messages to authenticated;
grant usage, select on sequence public.group_chat_messages_id_seq to authenticated;

create table if not exists public.group_chat_reads (
  message_id bigint not null references public.group_chat_messages(id) on delete cascade,
  user_id text not null,
  read_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

alter table public.group_chat_reads enable row level security;

drop policy if exists "Signed-in users can read group chat receipts" on public.group_chat_reads;
create policy "Signed-in users can read group chat receipts"
  on public.group_chat_reads for select
  to authenticated
  using (true);

drop policy if exists "Users can create their own group chat receipts" on public.group_chat_reads;
create policy "Users can create their own group chat receipts"
  on public.group_chat_reads for insert
  to authenticated
  with check ((auth.jwt() ->> 'sub') = user_id);

grant select, insert on public.group_chat_reads to authenticated;

create table if not exists public.call_availability (
  id uuid primary key default gen_random_uuid(),
  host_id text not null,
  starts_at timestamptz not null,
  duration_minutes smallint not null default 30 check (duration_minutes between 15 and 120),
  is_open boolean not null default true,
  created_at timestamptz not null default now(),
  unique (host_id, starts_at)
);

create table if not exists public.call_requests (
  id uuid primary key default gen_random_uuid(),
  availability_id uuid references public.call_availability(id) on delete cascade,
  host_id text not null,
  student_id text not null,
  message text not null default '' check (char_length(message) <= 500),
  status text not null default 'pending' check (status in ('pending', 'approved', 'declined')),
  room_id text unique,
  created_at timestamptz not null default now(),
  unique (availability_id, student_id)
);

create table if not exists public.call_rooms (
  id uuid primary key default gen_random_uuid(),
  created_by text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.call_room_members (
  room_id uuid not null references public.call_rooms(id) on delete cascade,
  user_id text not null,
  joined_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

alter table public.call_requests alter column availability_id drop not null;

drop index if exists public.call_requests_one_pending_room_per_student;
drop index if exists public.call_requests_one_approval_per_slot;

alter table public.call_availability enable row level security;
alter table public.call_requests enable row level security;
alter table public.call_rooms enable row level security;
alter table public.call_room_members enable row level security;

drop policy if exists "Room creators and members can read a room" on public.call_rooms;
create policy "Room creators and members can read a room"
  on public.call_rooms for select to authenticated
  using (
    created_by = (auth.jwt() ->> 'sub')
    or exists (
      select 1 from public.call_room_members member
      where member.room_id = call_rooms.id and member.user_id = (auth.jwt() ->> 'sub')
    )
  );

drop policy if exists "Users can create their own peer rooms" on public.call_rooms;
create policy "Users can create their own peer rooms"
  on public.call_rooms for insert to authenticated
  with check (created_by = (auth.jwt() ->> 'sub'));

drop policy if exists "Peers can read their own room membership" on public.call_room_members;
create policy "Peers can read their own room membership"
  on public.call_room_members for select to authenticated
  using (user_id = (auth.jwt() ->> 'sub'));

drop policy if exists "Peers can leave their own rooms" on public.call_room_members;
create policy "Peers can leave their own rooms"
  on public.call_room_members for delete to authenticated
  using (user_id = (auth.jwt() ->> 'sub'));

create or replace function public.join_call_room(p_room_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id text := auth.jwt() ->> 'sub';
begin
  if v_user_id is null then
    raise exception 'Sign in to join a peer room.';
  end if;
  if not exists (select 1 from public.call_rooms room where room.id = p_room_id) then
    raise exception 'Peer room not found.';
  end if;
  insert into public.call_room_members (room_id, user_id)
  values (p_room_id, v_user_id)
  on conflict (room_id, user_id) do nothing;
  return p_room_id;
end;
$$;

create or replace function public.leave_call_room(p_room_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id text := auth.jwt() ->> 'sub';
begin
  if v_user_id is null then
    raise exception 'Sign in to leave a peer room.';
  end if;
  delete from public.call_room_members
  where room_id = p_room_id and user_id = v_user_id;
end;
$$;

revoke all on function public.join_call_room(uuid) from public, anon;
revoke all on function public.leave_call_room(uuid) from public, anon;
grant execute on function public.join_call_room(uuid) to authenticated;
grant execute on function public.leave_call_room(uuid) to authenticated;
grant select, insert on public.call_rooms to authenticated;
grant select, delete on public.call_room_members to authenticated;

-- Keep historical request and availability rows, but turn off the old approval flow.
drop policy if exists "Anyone signed in can view open call slots" on public.call_availability;
drop policy if exists "Hosts manage their own call slots" on public.call_availability;
drop policy if exists "Students and hosts can read their call requests" on public.call_requests;
drop policy if exists "Students can request an open host slot" on public.call_requests;
drop policy if exists "Students can request a host room" on public.call_requests;
drop policy if exists "Hosts can approve or decline their requests" on public.call_requests;

drop policy if exists "Approved participants can receive call signaling" on realtime.messages;
drop policy if exists "Peer room members can receive call signaling" on realtime.messages;
create policy "Peer room members can receive call signaling"
  on realtime.messages for select to authenticated
  using (
    exists (
      select 1 from public.call_room_members member
      where member.room_id::text = split_part(realtime.topic(), 'video-call-', 2)
        and member.user_id = (auth.jwt() ->> 'sub')
    )
  );

drop policy if exists "Peer room members can send call signaling" on realtime.messages;
create policy "Peer room members can send call signaling"
  on realtime.messages for insert to authenticated
  with check (
    exists (
      select 1 from public.call_room_members member
      where member.room_id::text = split_part(realtime.topic(), 'video-call-', 2)
        and member.user_id = (auth.jwt() ->> 'sub')
    )
  );

revoke all on public.call_availability from anon, authenticated;
revoke all on public.call_requests from anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'group_chat_messages'
  ) then
    alter publication supabase_realtime add table public.group_chat_messages;
  end if;
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'group_chat_reads'
  ) then
    alter publication supabase_realtime add table public.group_chat_reads;
  end if;
  if exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'call_availability'
  ) then
    alter publication supabase_realtime drop table public.call_availability;
  end if;
  if exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'call_requests'
  ) then
    alter publication supabase_realtime drop table public.call_requests;
  end if;
end;
$$;

notify pgrst, 'reload schema';
